In [1]:
import numpy as np
l=[]
for i in range(1,7):
    l1=input("ENter the number: ")
    l.append(l1)
print(np.array(l))

ENter the number:  10
ENter the number:  20
ENter the number:  30
ENter the number:  40
ENter the number:  50
ENter the number:  60


['10' '20' '30' '40' '50' '60']


In [2]:
l.ndim()

AttributeError: 'list' object has no attribute 'ndim'

In [3]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [4]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)


[[1 2 3]
 [4 5 6]]


In [5]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [1]:
# Create a array which are containing all zero element using zeros()
all_zero=np.array(4)

NameError: name 'np' is not defined

In [2]:
# Create a array which are containing all zero element using zeros()
all_zeros=np.zeros(4)
print(all_zeros)

NameError: name 'np' is not defined

In [3]:
import numpy as np
all_zeros=np.zeros(4)
print(all_zeros)


[0. 0. 0. 0.]


In [10]:
all_zeros=np.zeros(4)
a_zeros=np.zeros((2,2,3))
print(all_zeros)
print()
print(a_zeros)
'''
- 2 blocks (outermost dimension)
- Each block has 2 rows
- Each row has 3 columns

'''

[0. 0. 0. 0.]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [6]:
all_zeros=np.zeros(4)
a_zeros=np.zeros(1,3)
print(all_zeros)
print(a_zeros)

TypeError: Cannot interpret '3' as a data type

In [11]:
new_array=np.zeros(1,2)
print(new_array)

TypeError: Cannot interpret '2' as a data type

In [16]:
new_array=np.zeros((1,2))
print(new_array
'''
- np.zeros((1, 2)) creates a 2D array with:
- 1 row
- 2 columns

'''

[[0. 0.]]


In [26]:
new_1D_array=np.zeros((2))
print(new_1D_array)
'''
- new_array.ndim → 1 (it's one-dimensional)
- new_array.shape → (2,) (just two elements in a single line)

'''


[0. 0.]


"\n- new_array.ndim → 1 (it's one-dimensional)\n- new_array.shape → (2,) (just two elements in a single line)\n\n"

In [29]:
# how to create an array which containing 1 inside of it
new_2D_array=np.ones((4,2))
print(new_2D_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [30]:
new_3D_array=np.ones((2,4,3))
print(new_3D_array)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [32]:
# how to create a an empty array using empty()
New_1D_array=np.empty(4)
print(New_1D_array)
'''
To fix the issue where an "empty" array unexpectedly contains values like 1.0, 
you should use np.zeros() or np.ones() instead of np.empty().

'''

[1. 1. 1. 1.]


In [36]:
# how to create an array using arrange function
new_array=np.arange((4))
print(new_array)
'''
To create an array using NumPy's arange() function, 
you can think of it like Python's built-in range() — but it returns a NumPy array instead of a list.
np.arange(start, stop, step)
- start: starting value (inclusive)
- stop: ending value (exclusive)
- step: increment (default is 1)
'''

[0 1 2 3]


"\nTo create an array using NumPy's arange() function, \nyou can think of it like Python's built-in range() — but it returns a NumPy array instead of a list.\nnp.arange(start, stop, step)\n- start: starting value (inclusive)\n- stop: ending value (exclusive)\n- step: increment (default is 1)\n"

In [37]:
new_array=np.arange(1,11)
print(new_array)
# if i am not giving increment decrement value the by default i will take 1 

[ 1  2  3  4  5  6  7  8  9 10]


In [46]:
# You can create a diagonal array using NumPy’s eye() function, 
# which generates a 2D array with ones on the main diagonal and zeros elsewhere.
# np.eye(N, M=None, k=0)
# - N: number of rows
# - M: number of columns (optional; defaults to N)
# - k: index of the diagonal
# - k=0: main diagonal
# - k>0: above the main diagonal
# - k<0: below the main diagonal
new_array=np.eye(3)
print(new_array)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
# 🎲 1. np.random.rand()
# Generates random floats in the range 0, 1) with a uniform distribution.
# import numpy as np

# arr = np.random.rand(2, 3)
# print(arr)


# Output:
# [[0.374 0.950 0.732]
#  [0.598 0.156 0.156]]



# 🧠 2. np.random.randn()
# Generates random numbers from a standard normal distribution (mean=0, std=1).
# arr = np.random.randn(2, 3)
# print(arr)


# Output:
# [[ 0.4967 -0.1383  0.6477]
#  [ 1.5230 -0.2341 -0.2341]]



# 🔢 3. np.random.randint()
# Generates random integers between a specified range.
# arr = np.random.randint(10, 100, size=(2, 3))
# print(arr)


# Output:
# [[45 67 89]
#  [23 78 56]]



# 📊 4. np.random.uniform()
# Generates random floats between low and high.
# arr = np.random.uniform(5, 15, size=(2, 3))
# print(arr)


# Output:
# [[ 6.23 14.56  9.87]
#  [12.34  5.67 10.45]]



# 📈 5. np.random.normal()
# Generates random numbers from a normal distribution with specified mean and standard deviation.
# arr = np.random.normal(loc=50, scale=10, size=(2, 3))
# print(arr)


# Output:
# [[48.23 52.45 60.12]
#  [39.87 47.56 55.34]]



# These outputs are examples — actual values will vary each time unless you set a seed using np.random.seed().
# Would you like to see how to set a seed for reproducibility or generate random arrays with specific shapes?


In [48]:
new_array=np.random.rand(2,3)
print(new_array)

[[0.94256026 0.54611265 0.69204341]
 [0.69065036 0.16858577 0.37891369]]


In [53]:
new_array=np.random.randn(2,3)
print(new_array)

[[-0.08885156 -0.26318791 -0.65040523]
 [-1.14119789  1.28033602 -0.36710917]]


In [54]:
new__array=np.random.randint(2,10,size=(2,3))
print(new__array)

[[5 4 2]
 [3 3 9]]


In [58]:
new_array=np.random.uniform(2,20,size=(2,3))
print(new_array)

[[ 4.16729849  6.15708595 17.44697924]
 [12.59014517 14.36644551 13.98896517]]


In [ ]:
# 1. Integer types (int8, int16, int32, int64)
# These represent whole numbers. The number after int indicates how many bits are used to store the value. More bits allow for a wider range of values. For example, int8 can store values from -128 to 127, while int64 can handle much larger numbers.
# 2. Unsigned integer types (uint8, uint16, uint32, uint64)
# These are like integer types but only store non-negative values. For example, uint8 ranges from 0 to 255. They're often used in image processing where pixel values are always positive.
# 3. Floating-point types (float16, float32, float64)
# These store decimal numbers. The number after float indicates the precision. float64 is the most precise and commonly used for scientific calculations.
# 4. Complex number types (complex64, complex128)
# These store complex numbers with real and imaginary parts. complex64 uses two 32-bit floats, and complex128 uses two 64-bit floats.
# 5. Boolean type (bool_)
# This stores True or False values. It's useful for logical operations, filtering, and masking arrays.
# 6. String types (str_, unicode_)
# These store text data. str_ is for ASCII strings, and unicode_ is for Unicode strings. You can specify the maximum length, like U10 for a Unicode string of up to 10 characters.
# 7. Object type (object_)
# This is a flexible type that can store any Python object. It's used when you need mixed types in one array or want to store custom objects.

# import numpy as np

# # Integer array
# arr_int = np.array([1, 2, 3], dtype='int32')

# # Float array
# arr_float = np.array([1.5, 2.5, 3.5], dtype='float64')

# # Boolean array
# arr_bool = np.array([True, False, True], dtype='bool')

# # Complex array
# arr_complex = np.array([1+2j, 3+4j], dtype='complex128')

# # String array
# arr_str = np.array(['apple', 'banana'], dtype='U10')

# # Object array
# arr_obj = np.array([1, 'text', True], dtype='object')

In [64]:
import numpy as np
new_array=np.array([10,20,30])
new_array1=new_array*2
print(new_array1)

[20 40 60]


In [66]:
l1=[10,20,30,40]
l2=np.array(l1)

print(l2*2)

[20 40 60 80]


In [ ]:
📐 shape of a NumPy Array
The shape attribute returns a tuple representing the number of elements along each dimension of the array.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
(2, 3)
This means the array has 2 rows and 3 columns.
=============================================================    
🔄 reshape() in NumPy
The reshape() method changes the shape of an array to a new configuration, as long as the total number of elements remains the same.
np.reshape(array, new_shape)
# or
array.reshape(new_shape)
   ================================================== 
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)
================================================
[[1 2 3]
 [4 5 6]]
================================================
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped = arr.reshape(2, 2, 2)
print(reshaped)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



In [ ]:
Broadcasting?
Broadcasting is a powerful feature in NumPy that lets you perform operations on arrays of different shapes without explicitly reshaping them.
    It works by replicating the smaller array along the missing dimensions so that both arrays become compatible for element-wise operations.

🧠 Broadcasting Rules
- If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on the left.
- Dimensions are compatible when:
- They are equal, or
- One of them is 1
- If shapes are not compatible, broadcasting fails with a ValueError.

✅ Examples
1. Scalar and Array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = arr + 10
print(result)


Output:
[[11 12 13]
 [14 15 16]]


Here, the scalar 10 is broadcasted to each element of the array.

2. 1D and 2D Arrays
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
result = a + b
print(result)


Output:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


The 1D array a is broadcasted across each row of the 2D array b.

3. Incompatible Shapes
a = np.array([1, 2])
b = np.array([[1, 2, 3], [4, 5, 6]])
# a + b → ValueError: operands could not be broadcast together


This fails because the shapes (2,) and (2, 3) are not compatible.

🔍 Why Broadcasting Is Useful
- Eliminates the need for manual reshaping or looping
- Makes code cleaner and faster
- Enables vectorized operations for performance

Would you like to see how broadcasting works with functions like np.mean() or in matrix multiplication?
Sources: GeeksforGeeks, Programiz, NumPy Docs.


In [77]:
array1=np.array([1,2,3,4]) #The array has 4 elements. It is a 1-dimensional array.So the shape is written as (4,) meaning: 4 rows (in 1D we simply say 4 elements)No second dimension
array2=np.array([[10],[20],[30]])
print(array1+array2)
print(array1.ndim)
print(array2.ndim)
print(array1.shape)
print(array2.shape)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
1
2
(4,)
(3, 1)


In [82]:
arr1=np.random.randint(10, 100, size=(3, 3))
arr2=np.random.randint(10,60, size=(3,1))
print(arr2)
print(arr1)
print(arr1+arr2)

[[53]
 [16]
 [50]]
[[72 82 94]
 [44 39 23]
 [35 55 17]]
[[125 135 147]
 [ 60  55  39]
 [ 85 105  67]]


In [ ]:
# Indexing and slicing in NumPy allow you to access and manipulate specific elements, rows, columns, or subarrays within a larger array. 
# These operations are fast, flexible, and essential for data analysis
# Indexing in NumPy
# Indexing means selecting specific elements from an array using their position.
# ✅ 1D Array Indexing
# import numpy as np
# arr = np.array([10, 20, 30, 40, 50])
# print(arr[2])  # Output: 30


# You can also use negative indexing to access elements from the end:
# print(arr[-1])  # Output: 50


# ✅ 2D Array Indexing
# arr2d = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr2d[1, 2])  # Output: 6


# This accesses the element in the second row, third column.

# ✂️ Slicing in NumPy
# Slicing extracts a portion of an array using the syntax start:stop:step.
# ✅ 1D Array Slicing
# arr = np.array([10, 20, 30, 40, 50])
# print(arr[1:4])  # Output: [20 30 40]


# You can also skip elements:
# print(arr[::2])  # Output: [10 30 50]


# ✅ 2D Array Slicing
# arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print(arr2d[0:2, 1:])  # Output: [[2 3] [5 6]]


# This selects rows 0 and 1, and columns 1 and 2.

# 🧠 Advanced Indexing
# You can use arrays of indices to select multiple elements:
# arr = np.array([10, 20, 30, 40, 50])
# indices = [0, 2, 4]
# print(arr[indices])  # Output: [10 30 50]



# 📌 Boolean Indexing
# Select elements based on conditions:
# arr = np.array([10, 20, 30, 40, 50])
# print(arr[arr > 30])  # Output: [40 50]



# These techniques make NumPy incredibly powerful for data manipulation.
# Sources: GeeksforGeeks, TutorialsPoint, NumPy Docs.
# Would you like to explore how slicing works with 3D arrays or masked arrays next?



In [86]:
array1=np.random.randint(10,50,size=(3,3))
print(array1)

[[42 30 43]
 [33 46 34]
 [37 34 30]]


In [89]:
print(array1[2][2])

30


In [92]:
arry1=np.random.randint(10,50,size=(3,3))
print(arry1)
print(arry1[2,0:])

[[33 13 16]
 [48 36 26]
 [16 25 17]]
[16 25 17]


In [ ]:
1. Iterating Over a 1D Array
import numpy as np

arr = np.array([10, 20, 30])
for element in arr:
    print(element)


Output:
10
20
30



🔁 2. Iterating Over a 2D Array (Row by Row)
arr2d = np.array([[1, 2], [3, 4]])
for row in arr2d:
    print(row)


Output:
[1 2]
[3 4]



🔁 3. Iterating Over Each Element (Flattened)
for element in arr2d.flat:
    print(element)


Output:
1
2
3
4



🔁 4. Using nditer() for Efficient Iteration
for x in np.nditer(arr2d):
    print(x)


Output:
1
2
3
4


This method is especially useful for multi-dimensional arrays and supports advanced options like read/write access and order control.

🔁 5. Iterating With Index Using ndenumerate()
for index, value in np.ndenumerate(arr2d):
    print(f"Index: {index}, Value: {value}")


Output:
Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4



Would you like to explore how to modify array elements during iteration or use vectorized operations instead of loops?


In [102]:
a1=np.random.randint(3,15,size=(8))
print(a1)
for i in a1:
    print(i)

[14  3  4 11  4  9  3  6]
14
3
4
11
4
9
3
6


In [105]:
ar1=np.random.randint(2,9,size=(2,4))
print(ar1)
for i in np.nditer(ar1):
    print(i)

[[6 8 2 4]
 [5 2 3 7]]
6
8
2
4
5
2
3
7


In [108]:
ar1=np.random.randint(2,9,size=(2,4))
for index, value in np.ndenumerate(ar1):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 6
Index: (0, 1), Value: 5
Index: (0, 2), Value: 8
Index: (0, 3), Value: 5
Index: (1, 0), Value: 4
Index: (1, 1), Value: 2
Index: (1, 2), Value: 6
Index: (1, 3), Value: 4


In [ ]:
Copy in NumPy
A copy creates a completely independent array. Changes to the original array do not affect the copy.
✅ Example
import numpy as np

a = np.array([1, 2, 3])
b = a.copy()
a[0] = 99

print("Original:", a)
print("Copy:", b)


Output:
Original: [99  2  3]
Copy:     [1  2  3]


🔹 b remains unchanged even though a was modified.

👀 View in NumPy
A view is a shallow copy — it references the same data. Changes to the original array do affect the view.
✅ Example
a = np.array([1, 2, 3])
b = a.view()
a[0] = 99

print("Original:", a)
print("View:", b)


Output:
Original: [99  2  3]
View:     [99  2  3]


🔹 b reflects the change because it shares the same data as a.

🔍 How to Check
You can check whether two arrays share memory using:
print(np.shares_memory(a, b))


- Returns True for views
- Returns False for copies

Would you like to explore how views behave with slicing or reshaping?


In [ ]:
Joining Arrays
Joining means combining multiple arrays into one. The most common functions are:
1. np.concatenate()
Joins arrays along an existing axis.
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.concatenate((a, b), axis=0)
print(result)


Output:
[[1 2]
 [3 4]
 [5 6]]



2. np.stack()
Joins arrays along a new axis.
a = np.array([1, 2])
b = np.array([3, 4])

result = np.stack((a, b), axis=0)
print(result)


Output:
[[1 2]
 [3 4]]



3. np.hstack() and np.vstack()
- hstack() → horizontal stack (along columns)
- vstack() → vertical stack (along rows)
a = np.array([1, 2])
b = np.array([3, 4])

print(np.hstack((a, b)))  # [1 2 3 4]
print(np.vstack((a, b)))  # [[1 2] [3 4]]



✂️ Splitting Arrays
Splitting means dividing one array into multiple sub-arrays.
1. np.split()
Splits an array into equal parts.
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)
print(result)


Output:
[array([1, 2]), array([3, 4]), array([5, 6])]



2. np.hsplit() and np.vsplit()
- hsplit() → splits along columns
- vsplit() → splits along rows
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.hsplit(arr, 3))  # 3 column-wise splits
print(np.vsplit(arr, 2))  # 2 row-wise splits



Would you like to see how to split arrays based on conditions or use array_split() for uneven splits?
==========================================================================================================================================
 Joining Arrays in NumPy
Joining means combining multiple arrays into one. The axis you choose determines how the arrays are joined.
Understanding axis
- axis=0 → join vertically (along rows)
- axis=1 → join horizontally (along columns)

Example: np.concatenate()
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Join vertically (add rows)
joined_v = np.concatenate((a, b), axis=0)
print("Vertical Join:\n", joined_v)

# Join horizontally (add columns)
joined_h = np.concatenate((a, b), axis=1)
print("Horizontal Join:\n", joined_h)


Output:
Vertical Join:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Join:
[[1 2 5 6]
 [3 4 7 8]]



Splitting Arrays in NumPy
Splitting means dividing one array into multiple sub-arrays. The axis determines how the array is split.
Example: np.split()
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Split along columns (axis=1)
split_h = np.split(arr, 2, axis=1)
print("Horizontal Split:")
for part in split_h:
    print(part)

# Split along rows (axis=0)
split_v = np.split(arr, 2, axis=0)
print("Vertical Split:")
for part in split_v:
    print(part)


Output:
Horizontal Split:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]

Vertical Split:
[[1 2 3 4]]
[[5 6 7 8]]



Summary
- Joining (axis=0) → stacks arrays vertically (adds rows)
- Joining (axis=1) → stacks arrays horizontally (adds columns)
- Splitting (axis=0) → splits by rows
- Splitting (axis=1) → splits by columns
Would you like to explore uneven splits using array_split() or visualize these operations with diagrams?



In [ ]:
Array Creation Functions
- np.array() – Create an array from a list or tuple
- np.zeros(), np.ones() – Arrays filled with 0s or 1s
- np.full() – Array filled with a specified value
- np.eye() – Identity matrix
- np.arange() – Evenly spaced values within a range
- np.linspace() – Evenly spaced values over an interval
- np.random.rand(), np.random.randint() – Random arrays

🔄 2. Array Manipulation
- np.reshape() – Change shape of an array
- np.ravel() – Flatten array
- np.transpose() – Swap axes
- np.resize() – Resize array
- np.append(), np.insert(), np.delete() – Modify arrays
- np.concatenate(), np.stack(), np.hstack(), np.vstack() – Join arrays
- np.split(), np.hsplit(), np.vsplit() – Split arrays

➕ 3. Arithmetic and Math Operations
- +, -, *, /, ** – Element-wise operations
- np.add(), np.subtract(), np.multiply(), np.divide()
- np.power(), np.mod(), np.reciprocal()
- np.exp(), np.log(), np.sqrt(), np.abs(), np.round()

📊 4. Statistical Functions
- np.mean(), np.median(), np.std(), np.var()
- np.min(), np.max(), np.sum(), np.prod()
- np.percentile(), np.quantile(), np.cumsum(), np.cumprod()

📐 5. Linear Algebra
- np.dot() – Dotoduct
- np.matmul() – Matrix multiplication pr
- np.linalg.inv() – Matrix inverse
- np.linalg.det() – Determinant
- np.linalg.eig() – Eigenvalues and eigenvectors
- np.linalg.solve() – Solve linear equations

🔍 6. Logical and Comparison
- np.where() – Conditional selection
- np.any(), np.all() – Logical checks
- np.equal(), np.greater(), np.less() – Comparisons
- np.logical_and(), np.logical_or(), np.logical_not()

🧠 7. Miscellaneous
- np.unique() – Unique elements
- np.sort(), np.argsort() – Sorting
- np.argmax(), np.argmin() – Index of max/min
- np.clip() – Limit values
- np.tile(), np.repeat() – Repeat patterns

📚 Full Reference
For a complete list of functions with examples, check out this excellent NumPy Cheat Sheet on GeeksforGeeks or the NumPy Functions PDF Cheatsheet.
Would you like a categorized PDF-style summary or a quiz to test your knowledge of these functions?


In [110]:
# Sort function 
var1=np.random.randint(10,30,size=20)
print(var1)

[28 23 16 15 15 14 28 22 14 18 25 18 29 24 21 25 22 19 26 11]


In [111]:
print(np.sort(var1))

[11 14 14 15 15 16 18 18 19 21 22 22 23 24 25 25 26 28 28 29]


In [112]:
np.sort(var1)

array([11, 14, 14, 15, 15, 16, 18, 18, 19, 21, 22, 22, 23, 24, 25, 25, 26,
       28, 28, 29], dtype=int32)

In [ ]:
🔀 np.random.shuffle()
Definition: Randomly shuffles the elements of an array in-place (modifies the original array).
Syntax:
np.random.shuffle(arr)


Example:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)


Output:
[3 1 5 2 4]  # (varies each time)



🧬 np.unique()
Definition: Returns the sorted unique elements of an array.
Syntax:
np.unique(arr)


Example:
arr = np.array([1, 2, 2, 3, 3, 3])
unique_vals = np.unique(arr)
print(unique_vals)


Output:
[1 2 3]



📐 np.resize()
Definition: Resizes an array to a new shape. If the new size is larger, it repeats elements.
Syntax:
np.resize(arr, new_shape)


Example:
arr = np.array([1, 2, 3])
resized = np.resize(arr, (2, 4))
print(resized)


Output:
[[1 2 3 1]
 [2 3 1 2]]



🧻 np.flatten()
Definition: Returns a copy of the array collapsed into 1D.
Syntax:
arr.flatten()


Example:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
print(flat)


Output:
[1 2 3 4]



🧨 np.ravel()
Definition: Returns a flattened view of the array (not a copy unless needed).
Syntax:
np.ravel(arr)


Example:
arr = np.array([[1, 2], [3, 4]])
flat_view = np.ravel(arr)
print(flat_view)


Output:
[1 2 3 4]



🔍 Difference Between flatten() and ravel()
- flatten() → returns a copy
- ravel() → returns a view (faster and memory-efficient)
Would you like to explore how these behave with multi-dimensional arrays or compare their performance?

==================================================================================================================
Yes, the flatten() method in NumPy does have an order parameter, which controls how the array is flattened
Syntax
array.flatten(order='C')


🧠 order Parameter Options
- 'C' (default): Row-major (C-style) — flattens row by row
- 'F': Column-major (Fortran-style) — flattens column by column
- 'A': 'F' if the array is Fortran-contiguous in memory, otherwise 'C'
- 'K': Flatten in the order the elements are stored in memory (preserves layout as much as possible)

✅ Example
import numpy as np

arr = np.array([[1, 2], [3, 4]])

print("C order:", arr.flatten(order='C'))  # [1 2 3 4]
print("F order:", arr.flatten(order='F'))  # [1 3 2 4]



So yes — if you want to control how the array is unraveled into 1D, the order parameter is your friend.
Would you like to see how this compares to ravel() or how memory layout affects performance?



In [116]:
var1=np.array([1,2,3,4,2,5,2,6,2,7])
x=np.unique(var1,return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9]), array([1, 4, 1, 1, 1, 1, 1]))


In [119]:
# Insert Function: used to insert the value at the given index position
a1=np.array([1,2,3,4,5,6])
print(a1)
v=np.insert(a1,(2,3),9)
v


[1 2 3 4 5 6]


array([1, 2, 9, 3, 9, 4, 5, 6])

In [121]:
# Delete Function in the numpy array: delete the element from array by providing the index position
var1=np.array([1,2,3,4,5])
print(var1)
var2=np.delete(var1,2)
print(var2)



[1 2 3 4 5]
[1 2 4 5]


In [125]:
matrix1=np.matrix([2,3])
print(matrix1)
print(matrix1.dtype)
print(matrix1.T)


[[2 3]]
int64
[[2]
 [3]]


In [129]:
m1=np.matrix([[2,4,6],[5,7,8]])
m2=np.matrix([[2,4,6],[5,7,8],[4,8,9]])
print(m1)
print()
print(m2)
print()
print(m1*m2)

[[2 4 6]
 [5 7 8]]

[[2 4 6]
 [5 7 8]
 [4 8 9]]

[[ 48  84  98]
 [ 77 133 158]]


In [ ]:
What Is a NumPy Matrix?
A matrix is a two-dimensional array with rows and columns. NumPy provides two ways to work with matrices:
- Using np.array() — preferred for general-purpose use
- Using np.matrix() — legacy class with matrix-specific behavior

✅ Creating a Matrix
import numpy as np

# Using array
arr = np.array([[1, 2], [3, 4]])

# Using matrix
mat = np.matrix([[1, 2], [3, 4]])

print("Array:\n", arr)
print("Matrix:\n", mat)



🔁 Matrix Operations
1. Transpose
print(mat.T)


2. Matrix Multiplication
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])

result = a * b  # matrix multiplication
print(result)


3. Inverse
inv = np.linalg.inv(mat)
print(inv)


4. Determinant
det = np.linalg.det(mat)
print(det)



⚠️ Note
- np.matrix is deprecated in favor of np.array with @ for matrix multiplication.
- Use @ operator or np.matmul() for matrix math with arrays:
result = arr @ arr.T



Would you like to explore solving linear equations or eigenvalues using NumPy matrices?
